commit:
  message-template: "{{.Type}} {{if .Scope}}({{.Scope}}): {{end}}{{.Summary}}"
  types:
    - text: 📝
      note: "docs"
      enable-scope: true
      scopes:
        - c
        - git
        - linux
        - others
    - text: 🎨
      note: "refactor"
    - text: 🔧
      note: "build"
    - text: 👷
      note: "ci"
