baseURL = "https://cqroot.github.io/"
locale = "en-us"
title = "Keith's Site"
theme = "docsy/theme"

[params]
favicon = "/favicon.svg"
offlineSearch = true

[params.ui]
showLightDarkModeMenu = true
sidebar_menu_compact = true
ul_show = 1
sidebar_menu_foldable = true
sidebar_cache_limit = 1000

[[menu.main]]
name = "Docs"
weight = 40
url = "/docs"

[[menu.main]]
weight = 50
url = "https://github.com/cqroot/cqroot.github.io"
pre = "<i class='fa-brands fa-github'></i>"
