// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  linuxSidebar: [{ type: "autogenerated", dirName: "linux" }],
  pythonSidebar: [{ type: "autogenerated", dirName: "python" }],
  vimSidebar: [{ type: "autogenerated", dirName: "vim" }],
  toolsSidebar: [{ type: "autogenerated", dirName: "tools" }],
  othersSidebar: [{ type: "autogenerated", dirName: "others" }],
};

export default sidebars;
