// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [{ type: "autogenerated", dirName: "docs" }],
  linuxSidebar: [{ type: "autogenerated", dirName: "linux" }],
  vimSidebar: [{ type: "autogenerated", dirName: "vim" }],
  toolsSidebar: [{ type: "autogenerated", dirName: "tools" }],
};

export default sidebars;
